export const TOGGLE_MAX_DEFROST = 'TOGGLE_MAX_DEFROST'
export const TOGGLE_FRONT_DEFROST = 'TOGGLE_FRONT_DEFROST'
export const TOGGLE_REAR_DEFROST = 'TOGGLE_REAR_DEFROST'

export const TOGGLE_AIR_RECIRCULATION = 'TOGGLE_AIR_RECIRCULATION'
export const TOGGLE_AC = 'TOGGLE_AC'
export const TOGGLE_AUTO = 'TOGGLE_AUTO'
export const TURN_AUTO_ON = 'TURN_AUTO_ON'
export const TURN_AUTO_OFF = 'TURN_AUTO_OFF'

export const SET_FAN_SPEED = 'SET_FAN_SPEED'
export const TOGGLE_FAN_DIR_FORWARD = 'TOGGLE_FAN_DIR_FORWARD'
export const TOGGLE_FAN_DIR_DOWN = 'TOGGLE_FAN_DIR_DOWN'
export const TOGGLE_FAN_DIR_UP = 'TOGGLE_FAN_DIR_UP'

export const ADVANCE_BOOT_SEQUENCE = 'ADVANCE_BOOT_SEQUENCE'
